
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace E_Commerce.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Advert
{

    public int AdvertId { get; set; }

    public string AdvertName { get; set; }

    public decimal Price { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<int> TempQuantity { get; set; }

    public Nullable<int> BrandId { get; set; }

    public Nullable<int> GenreId { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public string UserId { get; set; }



    public virtual Brand Brand { get; set; }

    public virtual Genre Genre { get; set; }

}

}
